name: Update CS Server Voice Channel
concurrency:
  group: update-cs-server-voice
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
jobs:
  update-channel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: node updateChannel.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          INTERVAL_MINUTES: 5
